from typing import List, Dict, Any, Literal, Optional
from pydantic import BaseModel, Field

class PositiveChunk(BaseModel):
    """Reference to the target positive chunk containing both its ID and raw text."""
    chunk_id: str
    content: str
    file_path: Optional[str] = None

class TrainingPair(BaseModel):
    """
    Core schema for all training pairs (synthetic or mined). 
    Used to build the final JSONL for contrastive learning.
    """
    anchor: str = Field(..., description="The user query or extracted docstring query text.")
    positive: PositiveChunk = Field(..., description="The correct target code chunk.")
    negatives: List[str] = Field(
        default_factory=list, 
        description="List of hard negative chunk IDs to push away during contrastive training."
    )
    source: Literal["mined", "synthetic"] = Field(
        ..., 
        description="Whether this was extracted directly from code (mined) or generated by an LLM (synthetic)."
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict, 
        description="Arbitrary metadata. Useful for tagging which Phase 1 failure cluster this pair addresses."
    )
